# Generated by Django 5.2.17 on 2026-09-14 01:04

from django.db import migrations


def populate_skill_interest_data(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    Interest = apps.get_model("main", "Interest")

    Skill.objects.get_or_create(
        name="Public Speaking & Internal Communication",
        defaults={
            "description": "Communicating ideas clearly and confidently in presentations, discussions, and internal communication.",
            "level": "Strong",
            "category": "Communication",
        },
    )

    Skill.objects.get_or_create(
        name="Teamwork & Collaboration",
        defaults={
            "description": "Working effectively with others, sharing responsibilities, and contributing to collaborative goals.",
            "level": "Strong",
            "category": "Collaboration",
        },
    )

    Skill.objects.get_or_create(
        name="English",
        defaults={
            "description": "English proficiency with a TOEFL ITP score of 573.",
            "level": "TOEFL ITP 573",
            "category": "Language",
        },
    )

    Skill.objects.get_or_create(
        name="Research & Data Analysis",
        defaults={
            "description": "Conducting research, organizing information, and analyzing data to support meaningful insights.",
            "level": "Intermediate",
            "category": "Research",
        },
    )

    Interest.objects.get_or_create(
        name="Exploring Bakeries",
        defaults={
            "description": "I enjoy discovering new bakeries and exploring different pastries and cozy spaces.",
            "category": "Lifestyle",
            "favorite_note": "Finding new favorite spots",
        },
    )

    Interest.objects.get_or_create(
        name="Gardening",
        defaults={
            "description": "I enjoy taking care of plants and spending quiet time around greenery.",
            "category": "Lifestyle",
            "favorite_note": "Growing little things",
        },
    )

    Interest.objects.get_or_create(
        name="Watching Movies",
        defaults={
            "description": "I enjoy watching movies as a way to relax and explore different stories and perspectives.",
            "category": "Entertainment",
            "favorite_note": "A good story always stays",
        },
    )

    Interest.objects.get_or_create(
        name="Swimming",
        defaults={
            "description": "I enjoy swimming as a refreshing activity and a way to stay active.",
            "category": "Well-being",
            "favorite_note": "A refreshing reset",
        },
    )


def remove_skill_interest_data(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    Interest = apps.get_model("main", "Interest")

    Skill.objects.filter(
        name__in=[
            "Public Speaking & Internal Communication",
            "Teamwork & Collaboration",
            "English",
            "Research & Data Analysis",
        ]
    ).delete()

    Interest.objects.filter(
        name__in=[
            "Exploring Bakeries",
            "Gardening",
            "Watching Movies",
            "Swimming",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_interest_skill"),
    ]

    operations = [
        migrations.RunPython(
            populate_skill_interest_data,
            remove_skill_interest_data,
        ),
    ]