# Generated by Django 5.2.17 on 2026-09-14 02:40
from django.db import migrations


def populate_experience_data(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")

    Experience.objects.all().delete()

    Experience.objects.create(
        title="BEM Fasilkom UI",
        description="Staff of Adkesma Department (Present) & SBF Adkesma Participant (2025).",
        category="part-time",
    )

    Experience.objects.create(
        title="Faculty Committees",
        description="COMPFEST 18 Media Partner Staff, BETIS Group Mentor (2026), DDP 0 Event Staff (2026), PSAF & PMB Group Mentor (2026).",
        category="volunteer",
    )

    Experience.objects.create(
        title="SMAN 90 Jakarta Organizations",
        description="Vice President of Youth Science Club (KIR), MPK Regeneration Commission Member, OSIS Language & Arts Division Member (2022 - 2024).",
        category="volunteer",
    )


def reverse_experience_data(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")
    Experience.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_populate_skill_interest_data"),
    ]

    operations = [
        migrations.RunPython(
            populate_experience_data,
            reverse_experience_data,
        ),
    ]