# Generated by Django 5.2.17 on 2026-09-14 02:46


from django.db import migrations


def update_bem_category(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")

    Experience.objects.filter(
        title="BEM Fasilkom UI"
    ).update(
        category="volunteer"
    )


def reverse_bem_category(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")

    Experience.objects.filter(
        title="BEM Fasilkom UI"
    ).update(
        category="part-time"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_populate_experience_data"),
    ]

    operations = [
        migrations.RunPython(
            update_bem_category,
            reverse_bem_category,
        ),
    ]